
relative_permalinks: false
highlighter: pygments
markdown: kramdown

baseurl: /jekyll-collection-issue

gems:
- jekyll-sitemap
- jekyll-feed

collections:
  items:
    output: true
    permalink: /things/:path/
